// Auth Action Types

export const AUTHENTICATE_USER = 'AUTHENTICATE_USER'
export const LOGOUT_USER = 'LOGOUT_USER'

// Auth App States

export const AUTHENTICATED = 'AUTHENTICATED'
export const UNAUNTHENTICATED = 'UNAUNTHENTICATED'
export const NOT_INITIALIZED = 'NOT_INITIALIZED'
export const AUTH_ERROR = 'AUTH_ERROR'