export const SET_GROUPS = 'SET_GROUPS';
export const ADD_GROUP = 'ADD_GROUP';
export const EDIT_GROUP = 'EDIT_GROUP';
export const REMOVE_GROUP = 'REMOVE _GROUP';
export const ADD_SUBCATEGORIES_TO_GROUP = 'ADD_SUBCATEGORIES_TO_GROUP';
export const DELETE_SUBCATEGORY_FROM_GROUP = 'DELETE_SUBCATEGORY_FROM_GROUP'; 
export const EDIT_SUBCATEGORY_FROM_GROUP = 'EDIT_SUBCATEGORY_FROM_GROUP';